### PR TITLE
Fix advanced subsubcommand (fixes #178)

### LINKED ISSUE #178: advanced subcommand doesn't handle subsubcommand in binjs_encode
running binjs_encode with advanced expanded uses multipart.
there's bug in from_matches.

### PR DESCRIPTION
**Pull request by arai-a**
given prividers are subsubcommand, we should first check the `advanced` subcommand there and check against `matches` for the subcommand.

### CODE REVIEW

File: crates/binjs_io/src/lib.rs [hunk 1]
```diff
@@ -414,14 +414,16 @@ impl Format {
     /// `matches` as a subcommand. If none, pick the default
     /// provider, without any command-line arguments.
     pub fn from_matches(matches: &clap::ArgMatches) -> Result<Self, std::io::Error> {
-        for provider in Self::providers().into_iter() {
-            let subcommand = provider.subcommand();
-            let key = subcommand.get_name();
-            if let Some(matches) = matches.subcommand_matches(key) {
-                return provider.handle_subcommand(Some(matches));
+        if let Some(matches) = matches.subcommand_matches("advanced") {
```
Comment (Yoric) [inline crates/binjs_io/src/lib.rs]: Mmmh... this puts half of `advanced` in encode.rs and half here.

Would it be possible to also make `fn providers()` private and replace it with a `pub fn subcommand() -> SubCommand` that would specify `"advanced"` from this file?

File: crates/binjs_io/src/lib.rs [hunk 2]
```diff
@@ -408,20 +408,30 @@ impl Format {
         &multipart::FormatProvider
     }
 
+    /// Returns command-line arguments.
```
Comment (Yoric) [inline crates/binjs_io/src/lib.rs]: Nit: Could you mention that advanced flags are hidden behind a command `"advanced"`?

Comment (Yoric) [reply crates/binjs_io/src/lib.rs]: Also, could you turn this `"advanced"` into a named constant?
