### PR TITLE
Resolve #406 - exit_binding_identifier now handles lazy functions

### LINKED ISSUE #406: Lazification broken on master
Looks like binast/binjs-ref@1b17153 this commit broke lazification.

Literally the one before it works, but trying to lazify anything with this one results in panics with `MissingBindingKind` error.

I guess this wasn't caught because we don't lazify things in tests.

### PR DESCRIPTION
**Pull request by Yoric**
exit_binding_identifier contains a hard-coded list of nodes that represent
functions. This is hardly ideal (perhaps we should somehow put this in the webidl?)
and at some point, we failed to update this list, causing the bug.

### CODE REVIEW

File: crates/binjs_es6/src/scopes.rs [hunk 1]
```diff
@@ -1153,81 +1174,39 @@ impl Visitor<ScopeError> for AnnotationVisitor {
...
+        Ok(None)
+    }
+
     fn exit_eager_function_declaration(
         &mut self,
         path: &WalkPath,
         node: &mut EagerFunctionDeclaration,
     ) -> ExitResult<EagerFunctionDeclaration> {
         debug!(target: "annotating", "exit_eager_function_declaration {:?} at {:?}", node.name.name, path);
+        self.exit_lazy_or_eager_function_declaration(path, &node.name)?;
```
Comment (RReverser) [inline crates/binjs_es6/src/scopes.rs]: In all of these, it seems you could just write:

```rust
self.exit_lazy_or_eager_function_declaration(path, &node.name)
```

and return result immediately?

Comment (Yoric) [reply crates/binjs_es6/src/scopes.rs]: The return type is different, unfortunately.

Comment (RReverser) [reply crates/binjs_es6/src/scopes.rs]: Ah. I guess you can make that function generic to return any `ExitResult<T>`?

**Comment by RReverser** [comment]
Seems fine by me, but I'll better leave it to you and @arai-a :)

**Comment by RReverser** [comment]
@Yoric Although, could you maybe change or re-enable tests responsible for lazification as part of this?
